server:
  port: 7777
  servlet:
    context-path: /clienta

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/server/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: client-a
          uri: http://localhost:7777/clienta/test
          predicates:
            - Path=/client-b

  application:
      name: zbz-client-a